/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import dto.*;
import controladores.*;
import java.time.LocalDate;
import java.time.format.DateTimeParseException;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author BrayanOcampo
 */
public class VentanaReserva extends javax.swing.JFrame {

    private HuespedControlador hControlador;
    private ReservaControlador rControlador;
    private HabitacionControlador habControlador;
    private VentanaMenu menu;
    
    public void setMenu(VentanaMenu menu) {
        this.menu = menu;
    }
    /**
     * Creates new form VentanaReserva
     */
    public VentanaReserva() {
        this.rControlador = new ReservaControlador();
        this.hControlador = new HuespedControlador();
        this.habControlador = new HabitacionControlador();
        initComponents();
        cargarHabitacionesDisponibles();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        DefaultTableModel modeloReservas = new DefaultTableModel(
        new Object[]{"ID", "Documento Huesped", "ID Habitacion", "Fecha Ingreso", "Fecha Salida"},
        0 // Sin filas al iniciar
        );
        tabla.setModel(modeloReservas);
    }

    private void cargarTablaReservas() {
    DefaultTableModel modelo = (DefaultTableModel) tabla.getModel(); // Obtener el modelo de la tabla
    modelo.setRowCount(0); // Limpiar todas las filas actuales

    ArrayList<ReservaDTO> lista = rControlador.obtenerTodasLasReservas(); // Obtener reservas 

    for (ReservaDTO r : lista) {
        Object[] fila = {
            r.getId(),
            r.getHuesped().getDocumento(),
            r.getHabitacion().getId(),
            r.getFechaEntrada().toString(),
            r.getFechaSalida().toString()
        };
        modelo.addRow(fila); // Agregar la fila al modelo
    }
}

    
    private void cargarHabitacionesDisponibles() {
    comboHabitacion.removeAllItems();
    ArrayList<HabitacionDTO> habitaciones = habControlador.obtenerTodasLasHabitaciones();
    for (HabitacionDTO hab : habitaciones) {
        comboHabitacion.addItem(hab.getId());
    }
}
    
    private void limpiarCamposReserva() {
        txtDocumentoHuesped.setText("");
        comboHabitacion.setSelectedIndex(0);
        txtFechaIngreso.setText("");
        txtFechaSalida.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lblDocHues = new javax.swing.JLabel();
        lblHab = new javax.swing.JLabel();
        lblFecIng = new javax.swing.JLabel();
        lblFechSal = new javax.swing.JLabel();
        txtDocumentoHuesped = new javax.swing.JTextField();
        comboHabitacion = new javax.swing.JComboBox<>();
        txtFechaIngreso = new javax.swing.JTextField();
        txtFechaSalida = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bttRegistrar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();
        bttMenu = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtFecIn = new javax.swing.JTextField();
        txtFecSa = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblHab1 = new javax.swing.JLabel();
        lblFecIng1 = new javax.swing.JLabel();
        lblFechSal1 = new javax.swing.JLabel();
        lblDocHues1 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        comboHab = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        bttBus = new javax.swing.JButton();
        bttEliminar = new javax.swing.JButton();
        bttEditar = new javax.swing.JButton();
        lblDocHues2 = new javax.swing.JLabel();
        txtDocHues = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(51, 102, 0));

        jPanel1.setBackground(new java.awt.Color(147, 147, 94));

        lblDocHues.setFont(new java.awt.Font("Arial Narrow", 3, 14)); // NOI18N
        lblDocHues.setForeground(new java.awt.Color(255, 255, 255));
        lblDocHues.setText("Documento huesped:");

        lblHab.setFont(new java.awt.Font("Arial Narrow", 3, 14)); // NOI18N
        lblHab.setForeground(new java.awt.Color(255, 255, 255));
        lblHab.setText("Habitación:");

        lblFecIng.setFont(new java.awt.Font("Arial Narrow", 3, 14)); // NOI18N
        lblFecIng.setForeground(new java.awt.Color(255, 255, 255));
        lblFecIng.setText("Fecha ingreso:");

        lblFechSal.setFont(new java.awt.Font("Arial Narrow", 3, 14)); // NOI18N
        lblFechSal.setForeground(new java.awt.Color(255, 255, 255));
        lblFechSal.setText("Fecha salida:");

        comboHabitacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(51, 102, 0));

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Reserva...");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        bttRegistrar.setFont(new java.awt.Font("Bookman Old Style", 3, 12)); // NOI18N
        bttRegistrar.setText("Registrar");
        bttRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttRegistrarActionPerformed(evt);
            }
        });

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        area.setEditable(false);
        area.setBackground(new java.awt.Color(147, 147, 94));
        area.setColumns(20);
        area.setFont(new java.awt.Font("Bookman Old Style", 2, 12)); // NOI18N
        area.setForeground(new java.awt.Color(255, 255, 255));
        area.setRows(5);
        area.setText("¡Bienvenido al EcoHotel Rural \"Raíces Verdes\"!\n\nUn lugar donde el descanso, la naturaleza y la sostenibilidad se encuentran.\nNuestro EcoHotel ofrece experiencias únicas rodeadas de paisajes naturales, \nconstrucciones ecológicas y un compromiso real con el medio ambiente.\nAquí, cada huésped es parte de una comunidad que valora el confort sin \ndejar de cuidar el planeta.");
        area.setAutoscrolls(false);
        area.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        area.setEnabled(false);
        area.setFocusable(false);
        area.setOpaque(false);
        jScrollPane2.setViewportView(area);

        bttMenu.setFont(new java.awt.Font("Bookman Old Style", 3, 12)); // NOI18N
        bttMenu.setText("Ir al menu");
        bttMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(170, 170, 170)
                                .addComponent(bttRegistrar))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(46, 46, 46)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(lblDocHues)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtDocumentoHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(lblHab)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(comboHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblFecIng)
                                                .addComponent(lblFechSal))
                                            .addGap(0, 0, Short.MAX_VALUE))))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(192, 192, 192)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtFechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addComponent(jScrollPane2))))
                .addContainerGap())
            .addComponent(bttMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDocHues)
                    .addComponent(txtDocumentoHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHab))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFecIng))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFechSal))
                .addGap(32, 32, 32)
                .addComponent(bttRegistrar)
                .addGap(32, 32, 32)
                .addComponent(bttMenu))
        );

        jTabbedPane1.addTab("Reservar", jPanel1);

        jPanel2.setBackground(new java.awt.Color(147, 147, 94));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(51, 102, 0));

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Disponibilidad...");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        lblHab1.setFont(new java.awt.Font("Arial Narrow", 3, 14)); // NOI18N
        lblHab1.setForeground(new java.awt.Color(255, 255, 255));
        lblHab1.setText("Habitación:");

        lblFecIng1.setFont(new java.awt.Font("Arial Narrow", 3, 14)); // NOI18N
        lblFecIng1.setForeground(new java.awt.Color(255, 255, 255));
        lblFecIng1.setText("Fecha ingreso:");

        lblFechSal1.setFont(new java.awt.Font("Arial Narrow", 3, 14)); // NOI18N
        lblFechSal1.setForeground(new java.awt.Color(255, 255, 255));
        lblFechSal1.setText("Fecha salida:");

        lblDocHues1.setFont(new java.awt.Font("Arial Narrow", 3, 14)); // NOI18N
        lblDocHues1.setForeground(new java.awt.Color(255, 255, 255));
        lblDocHues1.setText("Documento huesped:");

        comboHab.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        bttBus.setFont(new java.awt.Font("Bookman Old Style", 3, 12)); // NOI18N
        bttBus.setText("Buscar");
        bttBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttBusActionPerformed(evt);
            }
        });

        bttEliminar.setFont(new java.awt.Font("Bookman Old Style", 3, 12)); // NOI18N
        bttEliminar.setText("Eliminar");
        bttEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttEliminarActionPerformed(evt);
            }
        });

        bttEditar.setFont(new java.awt.Font("Bookman Old Style", 3, 12)); // NOI18N
        bttEditar.setText("Editar");
        bttEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttEditarActionPerformed(evt);
            }
        });

        lblDocHues2.setFont(new java.awt.Font("Arial Narrow", 3, 14)); // NOI18N
        lblDocHues2.setForeground(new java.awt.Color(255, 255, 255));
        lblDocHues2.setText("ID:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDocHues1)
                            .addComponent(lblHab1)
                            .addComponent(lblFecIng1)
                            .addComponent(lblFechSal1)
                            .addComponent(lblDocHues2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtDocHues, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bttBus, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboHab, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFecIn, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFecSa, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bttEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bttEliminar)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(27, 27, 27))
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDocHues2)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDocHues1)
                            .addComponent(bttBus)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDocHues, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHab1)
                    .addComponent(comboHab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttEliminar))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFecIng1)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtFecIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bttEditar)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFecSa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFechSal1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        jTabbedPane1.addTab("Disponibilidad", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttRegistrarActionPerformed
        // TODO add your handling code here:
        // Obtener datos del formulario
        String documento = txtDocumentoHuesped.getText().trim();
        String habitacionId = (String)comboHabitacion.getSelectedItem();
        String fechaIngreso = txtFechaIngreso.getText().trim();
        String fechaSalida = txtFechaSalida.getText().trim();

        // Validar que los campos no esten vacios
        if (documento.isEmpty() || habitacionId == null || fechaIngreso.isEmpty() || fechaSalida.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Completa todos los campos.");
            return;
        }

        try {
            // Validar formato de fechas y convertir a LocalDate
            LocalDate entrada = LocalDate.parse(fechaIngreso);
            LocalDate salida = LocalDate.parse(fechaSalida);

            // Obtener huesped y habitacion registrados 
            HuespedDTO huesped = hControlador.buscarHuesped(documento);
            HabitacionDTO habitacion = habControlador.buscarHabitacion(habitacionId);

            // Verificar que existan los datos
            if (huesped == null || habitacion == null) {
                JOptionPane.showMessageDialog(this, "Huesped o habitacion no encontrados.");
                return;
            }

            // Registrar la reserva
            rControlador.registrarReserva(documento + "-" + habitacionId, entrada, salida, huesped, habitacion);
                JOptionPane.showMessageDialog(this, "Reserva registrada.");
        limpiarCamposReserva();
        cargarTablaReservas(); 

    } catch (DateTimeParseException e) {
        // Manejo de error si las fechas no tienen el formato correcto
        JOptionPane.showMessageDialog(this, "Formato de fecha invalido. Usa YYYY-MM-DD.", "Error", JOptionPane.ERROR_MESSAGE);
    } catch (Exception ex) {
        // Manejo de cualquier otro error
        JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_bttRegistrarActionPerformed

    private void bttBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttBusActionPerformed
        // TODO add your handling code here:
        String id = txtID.getText().trim(); // Obtener el ID

    if (id.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Ingrese un ID para buscar");
        return;
    }

    ReservaDTO r = rControlador.buscarReserva(id);

    if (r != null) {
        txtID.setText(r.getHuesped().getDocumento());
        txtDocHues.setText(r.getHabitacion().getId());
        comboHabitacion.setSelectedItem(r.getHabitacion().getId());
        txtFecIn.setText(r.getFechaEntrada().toString());
        txtFecSa.setText(r.getFechaSalida().toString());
    } else {
        JOptionPane.showMessageDialog(this, "Reserva no encontrada");
    }
    }//GEN-LAST:event_bttBusActionPerformed

    private void bttEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttEliminarActionPerformed
        // TODO add your handling code here:
        String id = txtID.getText().trim();

        if (id.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el ID de la reserva a eliminar");
            return;
        }

        boolean eliminado = rControlador.eliminarReserva(id);

        if (eliminado) {
            JOptionPane.showMessageDialog(this, "Reserva eliminada");
            cargarTablaReservas(); // Refrescar la tabla
            limpiarCamposReserva();
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo eliminar");
        }
    }//GEN-LAST:event_bttEliminarActionPerformed

    private void bttEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttEditarActionPerformed
        // TODO add your handling code here:
        String documento = txtDocumentoHuesped.getText().trim();
        String fechaIngresoTexto = txtFechaIngreso.getText().trim();
        String fechaSalidaTexto = txtFechaSalida.getText().trim();
        String idHabitacion = (String) comboHabitacion.getSelectedItem();

        if (documento.isEmpty() || fechaIngresoTexto.isEmpty() || fechaSalidaTexto.isEmpty() || idHabitacion == null) {
            JOptionPane.showMessageDialog(this, "Completa todos los campos.");
            return;
        }

        try {
            LocalDate fechaIngreso = LocalDate.parse(fechaIngresoTexto);
            LocalDate fechaSalida = LocalDate.parse(fechaSalidaTexto);
        
            rControlador.editarReserva(documento, fechaSalida, fechaSalida);
            JOptionPane.showMessageDialog(this, "Reserva actualizada.");
            cargarTablaReservas();
            limpiarCamposReserva();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bttEditarActionPerformed

    private void bttMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttMenuActionPerformed
        // TODO add your handling code here:
        this.setVisible(false); // Ocultar esta ventana
            if (menu != null) {
            menu.setVisible(true); // Mostrar el menú principal
        }
    }//GEN-LAST:event_bttMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaReserva().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area;
    private javax.swing.JButton bttBus;
    private javax.swing.JButton bttEditar;
    private javax.swing.JButton bttEliminar;
    private javax.swing.JButton bttMenu;
    private javax.swing.JButton bttRegistrar;
    private javax.swing.JComboBox<String> comboHab;
    private javax.swing.JComboBox<String> comboHabitacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblDocHues;
    private javax.swing.JLabel lblDocHues1;
    private javax.swing.JLabel lblDocHues2;
    private javax.swing.JLabel lblFecIng;
    private javax.swing.JLabel lblFecIng1;
    private javax.swing.JLabel lblFechSal;
    private javax.swing.JLabel lblFechSal1;
    private javax.swing.JLabel lblHab;
    private javax.swing.JLabel lblHab1;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtDocHues;
    private javax.swing.JTextField txtDocumentoHuesped;
    private javax.swing.JTextField txtFecIn;
    private javax.swing.JTextField txtFecSa;
    private javax.swing.JTextField txtFechaIngreso;
    private javax.swing.JTextField txtFechaSalida;
    private javax.swing.JTextField txtID;
    // End of variables declaration//GEN-END:variables
}
